### registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Azimjon",
  "surname": "Nazarov",
  "email": "nazarovazimjon3@gmail.com",
  "password": "200622az"
}

### login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "200622az"
}

### init admin
GET localhost:8080/init/admin