### like
POST localhost:8080/comment_like/like/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzExOTQwNDEsImlkIjo0LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY3MTI4MDQ0MSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.0O1e-icrq4Dc6XMnLtfVfmtBVOAqxX1_7EKCMqvm6Za5DKnDHzmvzY1JAmcwrcQ2ahRQIXCkvoN9oOP9rlmP_w

### dislike
PUT localhost:8080/comment_like/dislike/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzExOTQwNDEsImlkIjo0LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY3MTI4MDQ0MSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.0O1e-icrq4Dc6XMnLtfVfmtBVOAqxX1_7EKCMqvm6Za5DKnDHzmvzY1JAmcwrcQ2ahRQIXCkvoN9oOP9rlmP_w

### remove
DELETE localhost:8080/comment_like/remove/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzExOTQwNDEsImlkIjo0LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY3MTI4MDQ0MSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.0O1e-icrq4Dc6XMnLtfVfmtBVOAqxX1_7EKCMqvm6Za5DKnDHzmvzY1JAmcwrcQ2ahRQIXCkvoN9oOP9rlmP_w


