### create
POST localhost:8080/profile/admin/create
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE2MTUyOTMsInVzZXJuYW1lIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzE3MDE2OTMsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.gdyztZzMZNQD8CuVDH6K0d2ZHGPQTc4sbx9zdT43RNfyTQsFuhr1HD0jlOwKjILUMchbquA7KCp9-fYlZCE6GQ

{
  "name": "publisher",
  "surname": "publish",
  "email": "publisher@gmail.com",
  "password": "200622az",
  "role": "ROLE_PUBLISHER"
}

### update admin
PUT localhost:8080/profile/admin/update
Content-Type:  application/json
Authorization: Basic admin@gmail.com d0435003d7ec62e6d7656dff18c42586


{
   "id": 1,
  "name": "A",
  "surname": "A",
  "password": "200622az"
}


### get list
GET localhost:8080/profile/admin/list?page=0&size=20
Authorization: Basic admin@gmail.com d0435003d7ec62e6d7656dff18c42586


### delete by id
DELETE localhost:8080/profile/delete/1
Authorization: Bearer


### filter
POST localhost:8080/profile/admin/filter?page=0&size=10
Content-Type: application/json
Authorization: Basic admin@gmail.com d0435003d7ec62e6d7656dff18c42586

{
  "fromDate":"2022-10-09",
  "toDate": "2022-12-14"
}